import { ApiProperty } from "@nestjs/swagger";
import { IsDecimal, Length } from "class-validator";

export class TwoFactorAuthenticationCodeDto {
    @ApiProperty({
        description: 'The 6-digit code generated by the authenticator app',
        type: String,
        format: '6-digit code',
        minLength: 6,
        maxLength: 6,
        example: '123456',
    })
    @IsDecimal()
    @Length(6, 6)
    code: string;
}